### ISSUE TITLE
Theme Fails with Spree 1.3.2

### ISSUE THREAD

**Issue by morytox** [spree-contrib/spree_blue_theme#11]
Theme install Fails with Spree 1.3.2

ActionView::Template::Error (Missing partial spree/shared/store_menu with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :coffee, :rabl], :versions=>[:v1]}. Searched in:
- "/Users/morytox/Projects/spreetut/mystore/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/spree_auth_devise-78342b5fa7c5/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/devise-2.2.3/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/spree_gateway-71fe33eee669/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/spree_gateway-71fe33eee669/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/bundler/gems/spree_gateway-71fe33eee669/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/spree_promo-1.3.2/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/spree_dash-1.3.2/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/spree_api-1.3.2/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/spree_core-1.3.2/app/views"
- "/usr/local/var/lib/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/kaminari-0.13.0/app/views"
  ):

**Comment by joshsticks** [comment]
Is anybody still watching this repo? Is there a better way to extend the core spree theme?

**Comment by GeekOnCoffee** [comment]
This repo is very old, it was the theme stripped out of 0.60.x for people looking to step up a version... Pull requests are welcome, however there's nobody really supporting it any more. 

It appears that https://github.com/spree/spree_blue_theme/pull/9 may solve the issue you're having, if you can test that and report back, we can get that merged...

In terms of extending the core theme, https://github.com/spree/spree_fancy is the official example of that. It's visible if you generate a sandbox from http://spreecommerce.com/. There's also https://github.com/spree/spree_rdr_theme although that is no longer supported either. 

We've done a lot of work to make an example not necessary for extending the theme; we have several guides on customization http://guides.spreecommerce.com/customization.html and there will be a blog post coming soon on how to extend the Spree Fancy theme.

**Comment by joshsticks** [comment]
Fantastic. Thanks so much for pointing me in the right direction. Keep up the good work.
