### ISSUE TITLE
css stoped working..

### ISSUE THREAD

**Issue by bitcoiners** [spree-contrib/spree_blue_theme#2]
Hello,
Something happened in the last few days.. between Rails 3.1 release, Spree git master updates,.. but css on spree_blue_theme stopped working..
my gemfile
gem 'rails', "~> 3.1.0"
..
gem 'spree', :git => 'git://github.com/spree/spree.git'
gem 'spree_blue_theme', :git => 'git://github.com/spree/spree_blue_theme.git'

and I get a home page with no styling.. Seems screen.css does not get included in all.css

p. s.
It used to work..

**Comment by runlevel5** [comment]
Are you production or development? And on heroku?

**Comment by bitcoiners** [comment]
I am in development, and currently running it on localhost.

**Comment by runlevel5** [comment]
Do you have 'sass-rails' in your Gemfile?

**Comment by bitcoiners** [comment]
group :assets do
  gem 'sass-rails', "~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

**Comment by runlevel5** [comment]
That's very peculiar. Can you tell me how you generate your sandbox? Mine is
working fine.

**Comment by bitcoiners** [comment]
oh.. never mind. I missed the rails g spree:site command in my sandbox. thanks.
