### ISSUE TITLE
sass-rails not load in heroku

### ISSUE THREAD

**Issue by runlevel5** [spree-contrib/spree_blue_theme#3]
Due to bug with sass-rails helper autoload, the compiled css does not compile <code>image-url</code> helper. Bug fix is already in upstream here:

https://github.com/rails/sass-rails/commit/1aa7daeb0a32648aeec4a3705b24c2b7543f615d

Will bump asap.

**Comment by GeekOnCoffee** [comment]
@joneslee85 is this still a valid issue?

**Comment by GeekOnCoffee** [comment]
Closing due to age. Feel free to comment if it's still an issue, and we'll reopen.
