### ISSUE TITLE
Installation missing steps?

### ISSUE THREAD

**Issue by scanferla** [spree-contrib/spree_blue_theme#4]
What am I supposed to do after adding 
`gem 'spree_blue_theme', :git => 'git://github.com/spree/spree_blue_theme.git'`
 to my Gemfile and running `bundle install` ?

I've done that but nothing changed. My store still without any theme, just the default `all.css`

Sorry if this is a silly question. But I really don't know what to do.

Thanks in advance,
Gustavo

**Comment by runlevel5** [comment]
Are you in development or production mode? There is no extra step but adding
the gem to your Gemfile.

**Comment by scanferla** [comment]
I'm in development mode and I've already done that.

Now I've just manually copied all files to my app to see what happens and the theme is now working!
Is this supposed to be this way?

Thanks :)

**Comment by runlevel5** [comment]
No, as long as your Gemfile has 'sass' and 'sass-rails', it should just
work. Can you please outline the steps you've taken?

**Comment by scanferla** [comment]
Sure!

Here is my Gemfile:

```
source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :production do  
  gem 'pg'
end

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

gem 'spree', :git => 'git://github.com/spree/spree.git'

gem 'spree_blue_theme', :git => 'git://github.com/spree/spree_blue_theme.git'

```

Steps I've taken:

Added to my Gemfile the following line:
```gem 'spree_blue_theme', :git => 'git://github.com/spree/spree_blue_theme.git'

``````

And ``` bundle install ```

Am I missing something?

Thanks :)

``````

**Comment by runlevel5** [comment]
No, you aren't missing anything. It's just weird how yours doesn't work. Can
you please paste your all.css into a gist and send me the link?

**Comment by scanferla** [comment]
Sure, here is the link: https://gist.github.com/1211263
_(why this is just ".css" and not ".css.scss"?)_

And what is generated: https://gist.github.com/1211267

**Comment by runlevel5** [comment]
That's very peculiar, have you run bundle exec rake assets:compile
RAILS_ENV=development

**Comment by scanferla** [comment]
It's working now! 
I should have known this or this is some kind of "missing step"?

Thanks! :)

**Comment by DavidOliver** [comment]
I'm getting this, too, on my dev machine. I don't want to do `bundle exec rake assets:compile RAILS_ENV=development` because:

> Using the precompile rake task in development will prevent any changes to asset files from being automatically loaded in when you reload the page. You must re-run the precompile task for changes to become available.

Here's my Gemfile:

```
source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2'
gem 'spree'
gem 'spree_blue_theme', :git => 'git://github.com/spree/spree_blue_theme.git'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
```

I'm using RVM on my dev machine.

Here is where the gem is installed to:

```
$ bundle show spree_blue_theme
/home/david/.rvm/gems/ruby-1.9.2-p290@ereptile-shop/bundler/gems/spree_blue_theme-d1e95e7b0179
```

The blue theme overrides are being used, but the assets are not being served by the assets pipeline.

Is this a manifest issue?

**Comment by DavidOliver** [comment]
I've updated my production server with the Gemfile above, and after precompiling and restarting the app the blue theme's assets are appearing.

So how can we use the blue theme without precompiling assets in the development environment?

Thanks.

**Comment by DavidOliver** [comment]
Progress! Quite by chance, I came across http://railscasts.com/episodes/298-getting-started-with-spree which indicates the following needs to be added to all.css:

```
 *= require store/screen
```

Doing this does indeed load the CSS, but some of the spacing still seems wrong...

http://dl.dropbox.com/u/183085/spree-blue.png

**Comment by DavidOliver** [comment]
I've watched the relevant bit of the screencast now, and Ryan replaces:

```
 *= require store/spree_core
 *= require store/spree_auth
 *= require store/spree_api
 *= require store/spree_promo
 *= require store/spree_dash
```

with

```
 *= require store/screen
```

(I was adding store/screen to the end of that block. When replacing that block, the spacing is okay.

Is this the correct way of handling it? Ryan says in the screencast he's not sure if it is completely correct.

**Comment by GeekOnCoffee** [comment]
Closing due to age. Feel free to comment if it's still an issue, and we'll reopen.
