### ISSUE TITLE
Layout missplaced

### ISSUE THREAD

**Issue by Arrumaco** [spree-contrib/spree_blue_theme#6]
Hi,

I'm developing 2 stores, both with spree 0.70.1. Recently I added the blue_theme to the first store and after some problems it worked fine. One week after I built the second store and repeated the same steps made with the first one. In this new store, the blue theme looks misplaced at the left side, showing the taxons menu totally aligned to the left (in the first store -the good one- all the taxons menu shows indented and inside the gray rectangle next to the products images.

After some research I found that the div id="wrapper" missed the class="container". If in debug mode on FF add this class, the page shows great!.

In the "Port to Spree 1.0.0" commit, I found that in 'add_class_to_wrapper.rb', the :virtual_path => 'spree/layouts/spree_application' is the cause of my problem (the good store uses the spree_blue_theme-d1e95e7b0179 commit and :virtual_path => 'layouts/spree_application'). Finally, if i change the  'add_class_to_wrapper.rb' and remove 'spree/' from the virtual_path, the new store works fine too.

Is it a issue in the new version 0.2.0 or Am I doing something wrong?

**Comment by runlevel5** [comment]
Thanks for spotting that out, fix is coming

Trung LÊ

**Comment by runlevel5** [comment]
EDIT: there is nothing wrong with the master branch. The master branch is
now used for spree version 1.0.0. For Spree 0.70.1, please change your
Gemfile

gem 'spree_blue_theme', :git => 'git://github.com/spree/spree_blue_theme.git',
:branch => '0-70-stable'

Cheers

**Comment by Arrumaco** [comment]
Thanks a lot. Adding the :branch => '0-70-stable', fixed the problem and it is working fine now!.

**Comment by victorhazbunanuff** [comment]
THANKS GOD!
